### ISSUE TITLE
Won't compile on ubuntu 18.04

### ISSUE THREAD

**Issue by waterfallm** [Centexio/Centex#1]
error on make command

ECDSA_SIG*, const unsigned char*, int, int, int)';
exwrapper.cpp:62:28 error: invalid use of incomplete type 'ECDSA_SIG...
